package com.example.jorgealberto.researchmobile.SQL;

public class sql_select {

	//public static String GET_OPCAO_ALEATORIO = " SELECT ID_PERGUNTA, DESCRICAO, ORDENA FROM PERGUNTAS WHERE DESCRICAO LIKE '%[[RA%'";

	//public static String GET_OPCAO_ALEATORIO2 = " SELECT ID_PERGUNTA, DESCRICAO, ORDENA FROM PERGUNTAS WHERE ORDENA >= ? AND ORDENA <= ? order by ORDENA ";


    //public static String GET_personalizacaocidade = " SELECT O.ID_OPCAO, O.OPCAO, O.ID_PERGUNTA, O.ORDENA, O.VALOR FROM OPCAO O WHERE  O.ID_PERGUNTA = 2 AND ?  ";

	public static String GET_completo = " select id_aluno from resposta where id_pergunta = ? and id_aluno = ? ";

	public static String get_contapergunta = " select max(id_pergunta) from PERGUNTAS ";

	public static String getPersonalizacao_opcao = " SELECT O.ID_OPCAO, O.OPCAO, O.ID_PERGUNTA, O.ORDENA, O.VALOR, R.VALOR  FROM OPCAO O, RESPOSTA R WHERE O.ID_OPCAO = R.ID_OPCAO and O.ID_PERGUNTA = R.ID_PERGUNTA AND O.ID_PERGUNTA = ? and R.id_aluno = ?  ";

	public static String getPersonalizacao_opcao_opcao = " SELECT O.ID_OPCAO, O.OPCAO, O.ID_PERGUNTA, O.ORDENA, O.VALOR  FROM OPCAO O WHERE O.ID_PERGUNTA = ? and O.ID_OPCAO = ? ";




	public static String GET_tem_controle_inicio = " SELECT ID_USUARIO, NM_USUARIO, LONGITUDE, LATITUDE, DATA_INICIO, INICIO  FROM CONTROLE_INICIO WHERE ID_aluno = ?";

	public static String get_todos_alunos = " select distinct id_aluno from resposta ";

	public static String GET_tem_controle_fim= " SELECT * FROM CONTROLE_FIM WHERE ID_aluno = ? ";



	public static String GET_OPCAO_FAMILIA_SEXO = " SELECT SEXO FROM ALUNO WHERE ID_ALUNO = ? ";
	public static String GET_OPCAO_FAMILIA = " SELECT NOME FROM ALUNO WHERE SEXO = ? ";


	public static String GET_teste_duda = " select R.ID_ALUNO, R.valor from t_resposta r where id_pergunta = 13  ";


	public static String GET_BUSCA_SUBPERGUNTA = " SELECT R.VALOR, R.ID_PERGUNTA, R.ID_OPCAO, R.ID_OPCAO_PESSOA, O.OPCAO, O.VALOR  FROM RESPOSTA R, OPCAO O, PERGUNTAS P WHERE P.ID_PERGUNTA = R.ID_PERGUNTA AND P.ID_PERGUNTA = P.ID_PERGUNTA AND  R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND P.NUM_SUBFORMULARIO = ? AND R.ID_OPCAO_PESSOA > 0  order by R.ID_OPCAO_PESSOA, R.ID_PERGUNTA, R.ID_OPCAO  ";


	public static String GET_RESPOSTA_subformulario = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO, R.ID_OPCAO_PESSOA   FROM RESPOSTA R, OPCAO O, PERGUNTAS P "+
	" WHERE P.ID_PERGUNTA = R.ID_PERGUNTA AND P.ID_PERGUNTA = O.ID_PERGUNTA AND R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_OPCAO_PESSOA = ? AND P.NUM_SUBFORMULARIO ORDER BY R.ID_OPCAO_PESSOA, R.ID_PERGUNTA, R.ID_OPCAO  ";


	public static String GET_OBRIGATORIO = " SELECT MINIMO FROM OPCAO WHERE ID_OPCAO = ? ";









    public static String GET_BUG1 = " SELECT * FROM CONTROLE_INICIO WHERE ID_USUARIO IS NULL OR ID_USUARIO = 0 ";

	public static String GET_BUG2 = " SELECT * FROM CONTROLE_FIM WHERE ID_USUARIO IS NULL OR ID_USUARIO = 0 ";

	//public static String GET_CONTROLE_INICIO = " SELECT A.ID_ALUNO, A.ID_USUARIO, A.NM_USUARIO, A.DATA_INICIO, A.INICIO, A.LONGITUDE, A.LATITUDE, A.GRAVACAO, A.NM_PESQUISA, A.PREVISAO FROM CONTROLE_INICIO A WHERE A.ID_ALUNO = (SELECT DISTINCT B.ID_ALUNO FROM CONTROLE_INICIO B WHERE A.ID_ALUNO = B.ID_ALUNO) wwwww  where ID_ALUNO = 2 ";
	
	
	public static String GET_CONTROLE_INICIO = " SELECT ID_ALUNO ID_ALUNO, ID_USUARIO, NM_USUARIO, DATA_INICIO, INICIO, LONGITUDE, LATITUDE, GRAVACAO, NM_PESQUISA, PREVISAO FROM CONTROLE_INICIO C WHERE ID_ALUNO = (SELECT DISTINCT ID_ALUNO FROM resposta R where C.id_aluno = R.id_aluno) ";

	
	public static String GET_CONTROLE_FIM = " SELECT ID_ALUNO, ID_USUARIO, NM_USUARIO, DATA_FIM, FIM, LONGITUDE, LATITUDE FROM CONTROLE_FIM C WHERE ID_ALUNO = (SELECT DISTINCT ID_ALUNO FROM resposta R where C.id_aluno = R.id_aluno)  ";
	
	public static String GET_PESQUISA = " SELECT ID_CLIENTE, ID_PESQUISA, DSC_PESQUISA, AUTOMATICO FROM PESQUISA ";

	public static String GET_PESQUISA_usuario = " SELECT P.ID_CLIENTE, P.ID_PESQUISA, P.DSC_PESQUISA, P.AUTOMATICO, P.PREVISAO FROM PESQUISA P, USUARIO U, PESQUISA_USUARIO PU WHERE PU.ID_PESQUISA = P.ID_PESQUISA AND PU.ID_CLIENTE = P.ID_CLIENTE AND PU.ID_USUARIO = U.ID AND U.ID_CLIENTE = P.ID_CLIENTE AND U.NM_USUARIO = ?   ";
	
	
	public static String GET_PESQUISA_nome = " SELECT ID_CLIENTE, ID_PESQUISA, DSC_PESQUISA, AUTOMATICO FROM PESQUISA WHERE DSC_PESQUISA = ? ";

	public static String GET_PESQUISA_usuarioeee = " SELECT ID ,    ID_PESQUISA  , ID_USUARIO ,    ID_CLIENTE FROM PESQUISA_USUARIO ";
	
	
	public static String GET_ESCOLA = " SELECT ID_ESCOLA, NOME_ESCOLA FROM ESCOLA ";
	
	public static String GET_TURMA = " SELECT ID_TURMA, NOME_TURMA FROM TURMA ";
	
	public static String GET_TURMA_parametro = " SELECT T.ID_TURMA, T.NOME_TURMA FROM TURMA T, ESCOLA E WHERE E.ID_ESCOLA = T.ID_ESCOLA AND E.ID_ESCOLA = ? ";
	
	public static String GET_USUARIO = " SELECT NM_USUARIO, SENHA, ID FROM USUARIO WHERE NM_USUARIO = ? AND SENHA = ? ";
	
	public static String GET_USUARIO2 = " SELECT NM_USUARIO, SENHA, ID FROM USUARIO WHERE NM_USUARIO = ? ";
	
	public static String GET_ALUNO_MAX = " SELECT MAX(ID_ALUNO) FROM ALUNO ";
	
	public static String GET_ALUNO = " SELECT distinct P.ID_ALUNO, P.NOME, R.ID_ALUNO FROM ALUNO P LEFT OUTER JOIN RESPOSTA R ON P.ID_ALUNO = R.ID_ALUNO WHERE (1 = 1) ";
	
	//public static String GET_ALUNO_completo = " SELECT ID_ALUNO, ID_ESCOLA, ID_TURMA , NOME, DT_NASC, SEXO FROM ALUNO WHERE  " ;
	
	public static String GET_ALUNO_completoNOVO = " SELECT distinct A.ID_ALUNO, A.ID_ESCOLA, A.ID_TURMA , A.NOME, A.DT_NASC, A.SEXO FROM ALUNO A, RESPOSTA R WHERE A.ID_ALUNO = R.ID_ALUNO  " ;
	
	public static String GET_PERGUNTA_CONTA = " SELECT MAX(ID_PERGUNTA) FROM PERGUNTAS ";

	public static String GET_PERGUNTA_CONTA_mim = " SELECT MIN(ID_PERGUNTA) FROM PERGUNTAS ";
	
	public static String GET_MAX_SALTO = " SELECT MAX(SALTO), ID_PERGUNTA FROM OPCAO ";
	
	public static String GET_PERGUNTA_CHECK = "  SELECT MAX(ID_PERGUNTA) FROM RESPOSTA WHERE ID_ALUNO =  ?  ";
	
	public static String GET_PERGUNTA_QUESTIONARIO =  " SELECT O.ID_PERGUNTA, O.ID_OPCAO, O.SALTO, " +
		    " O.ID_OPCAO, O.OPCAO, O.MAXIMO, O.VALOR, " +
		    " P.DESCRICAO, B.ID_BLOCO, B.DESCBLOCO, B.INFORMACAO, O.MINIMO " +
		    " FROM OPCAO O, PERGUNTAS P, BLOCO B " +
		    " WHERE O.ID_PERGUNTA = P.ID_PERGUNTA AND B.ID_BLOCO = P.ID_BLOCO ORDER BY O.ID_PERGUNTA, O.ID_OPCAO; ";

	public static String GET_PERGUNTA_QUESTIONARIO_NOVO =  " SELECT P.ID_PERGUNTA, P.DESCRICAO, B.ID_BLOCO, B.DESCBLOCO, B.INFORMACAO, P.NUM_SUBFORMULARIO, P.ID_PERGUNTA_JSON, P.COD_PERGUNTA  " +
			" FROM PERGUNTAS P, BLOCO B " +
			" WHERE B.ID_BLOCO = P.ID_BLOCO ORDER BY  P.ORDENA ; ";

	//public static String GET_respostaJson = " SELECT P.ID_PERGUNTA, P.ID_OPCAO FROM RESPOSTA WHERE ID_ALUNO = ? ";
	public static String GET_respostaJson = " SELECT ID_PERGUNTA, ID_OPCAO FROM RESPOSTA ";


	public static String GET_PERGUNTA_QUESTIONARIO_FI =  " SELECT P.ID_PERGUNTA, P.DESCRICAO, B.ID_BLOCO, B.DESCBLOCO, B.INFORMACAO " +
		    " FROM PERGUNTAS P, BLOCO B " +
		    " WHERE B.ID_BLOCO = P.ID_BLOCO and (P.ID_PERGUNTA < 19 or P.ID_PERGUNTA = 100) ORDER BY  P.ID_PERGUNTA ; ";

	public static String GET_PERGUNTA_QUESTIONARIO_OG=  " SELECT P.ID_PERGUNTA, P.DESCRICAO, B.ID_BLOCO, B.DESCBLOCO, B.INFORMACAO " +
			" FROM PERGUNTAS P, BLOCO B " +
			" WHERE B.ID_BLOCO = P.ID_BLOCO and ((P.ID_PERGUNTA > 18 AND P.ID_PERGUNTA < 37) or P.ID_PERGUNTA = 1  or P.ID_PERGUNTA = 100) ORDER BY  P.ID_PERGUNTA ; ";


	public static String GET_PERGUNTA_QUESTIONARIO_FG =  " SELECT P.ID_PERGUNTA, P.DESCRICAO, B.ID_BLOCO, B.DESCBLOCO, B.INFORMACAO " +
			" FROM PERGUNTAS P, BLOCO B " +
			" WHERE B.ID_BLOCO = P.ID_BLOCO and ((P.ID_PERGUNTA > 36) or P.ID_PERGUNTA = 1 or P.ID_PERGUNTA = 100) ORDER BY  P.ID_PERGUNTA ; ";


	public static String GET_SALTO =  " SELECT ID_SALTO, SALTO_PARA, PERGUNTA, ITEM_PERGUNTA FROM SALTO ORDER BY SALTO_PARA ";
	
	
	public static String GET_PERGUNTA =
			" SELECT ID_PERGUNTAS, DESCRICAO, ID_BLOCO " +
	" FROM PERGUNTAS  ";
	//" WHERE ID_PERGUNTAS = ? ";



	public static String GET_PERGUNTA_PERSONALIZACAO =
			" SELECT ID_PERGUNTA, ID_OPCAO, VALOR  " +
					" FROM RESPOSTA  " +
	" WHERE ID_PERGUNTA = ? AND ID_ALUNO = ? ";


	public static String GET_PERGUNTA_PERSONALIZACAO_OPCAO =
			" SELECT ID_PERGUNTA, ID_OPCAO, VALOR  " +
					" FROM RESPOSTA  " +
					" WHERE ID_PERGUNTA = ? AND ID_ALUNO = ? AND ID_OPCAO = ? ";

	public static String GET_PERGUNTA_PERSONALIZACAO_OPCAO_NOVA =
			" SELECT ID_PERGUNTA, ID_OPCAO, VALOR  " +
					" FROM RESPOSTA  " +
					" WHERE ID_PERGUNTA = ? AND ID_ALUNO = ?  ";
	
	public static String GET_OPCAO =
			" SELECT ID_OPCAO, MAXIMO, VALOR, OPCAO, MINIMO, ID_PERGUNTA, SALTO, ORDENA, PERSONALIZACAO " +
	" FROM OPCAO  "+
	" WHERE ID_PERGUNTA = ? ORDER BY ORDENA, ID_OPCAO ";
	
	public static String GET_OPCAO_OPCAO =
			" SELECT ID_OPCAO, MAXIMO, VALOR, OPCAO, MINIMO, ID_PERGUNTA, SALTO, ORDENA " +
	" FROM OPCAO  "+
	" WHERE ID_PERGUNTA = ? AND ID_OPCAO = ? order by ID_PERGUNTA, ID_OPCAO";
	
	public static String GET_MAX_OPCAO = " SELECT MAX(ID_OPCAO) FROM OPCAO ";

	public static String GET_ALIMENTOS =
			" SELECT ID, DESCRICAO, ID_ALUNO, CODIGO " +
					" FROM ALIMENTO  "+
					" WHERE ID_ALUNO = ? ";

	public static String GET_ALIMENTOS_nome =
			" SELECT ID, DESCRICAO, ID_ALUNO " +
					" FROM ALIMENTO  "+
					" WHERE ID = ? ";

	public static String GET_MODO_PREPARACAO =
			" SELECT ID_ALUNO, DESCRICAO " +
					" FROM MODO_PREPARACAO  "+
					" WHERE ID_ALIMENTO = ? ";

	public static String GET_TUDO_ALIMENTO_CHECADO =
			" SELECT  ID_PERGUNTA FROM perguntas where cod_pergunta = 'DETALIM/2' ";

	public static String GET_ALIMENTO_INSERIDO =
			" SELECT  ID_PERGUNTA FROM perguntas where cod_pergunta = 'ALIMENTO/10' ";

	public static String GET_ADICOES =
			" SELECT ID_ALUNO, DESCRICAO " +
					" FROM ADICOES  "+
					" WHERE ID_ALIMENTO = ? ";

	public static String GET_MEDIDAS_CASEIRAS =
			" SELECT ID_ALUNO, DESCRICAO " +
					" FROM MEDIDAS_CASEIRAS  "+
					" WHERE ID_ALIMENTO = ? ";
	
	
	//public static String GET_PERGUNTA_COMPLETA =
	//		" SELECT P.ID_PERGUNTAS, P.DESCRICAO, O.OPCAO, O.VALOR " +
	//" FROM PERGUNTAS P, OPCAO O WHERE O.ID_PERGUNTA = P.ID_PERGUNTAS "+
	//" AND P.ID_PERGUNTA = 3; ";
	
	public static String GET_PERGUNTA_COUNT =
			" SELECT COUNT(*) " +
	" FROM PERGUNTAS P, OPCAO O WHERE O.ID_PERGUNTA = P.ID_PERGUNTA and P.ID_PERGUNTAS = 1; ";
	//" WHERE ID_PERGUNTAS = ? ";
	
	public static String GET_RESPOSTA_3 = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
	" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";
	
	public static String GET_RESPOSTA_1 = " SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA   FROM RESPOSTA R, OPCAO O "+
	" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND (R.ID_OPCAO_PESSOA IS NULL OR R.ID_OPCAO_PESSOA = 0)   ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";


	public static String GET_RESPOSTA_OPCAO_TOTAS = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? AND R.ID_OPCAO = ? AND R.ID_ALIMENTO = ? ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";


	public static String GET_RESPOSTA_OPCAO_NOME_ALIMENTO = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? AND O.OPCAO = 'Nome do alimento' ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";

	public static String GET_RESPOSTA_OPCAO_MEDIDA_CASEIRA = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? AND O.OPCAO = 'Medida caseira' ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";

	public static String GET_RESPOSTA_OPCAO_MODO_PREPARACAO = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? AND O.OPCAO = 'Modo de preparação' ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";

	public static String GET_RESPOSTA_OPCAO_QUANTIDADE_MEDIDAS = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? AND O.OPCAO = 'Quantidade de medidas utilizada' ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";

	public static String GET_RESPOSTA_OPCAO_TOTAS_MAIOR_3 = "SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA, O.OPCAO   FROM RESPOSTA R, OPCAO O"+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND R.ID_PERGUNTA = ? AND R.ID_ALIMENTO = ?  ORDER BY R.ID_PERGUNTA, R.ID_OPCAO ";



	public static String GET_RESPOSTA_VIRTUAL = " SELECT DISTINCT ID_PERGUNTA FROM RESPOSTA WHERE ID_ALUNO = ? ";

	public static String GET_RESPOSTA = " SELECT ID_ALUNO, ID_PERGUNTA, ID_OPCAO, VALOR FROM RESPOSTA order by VALOR desc ";
	
	public static String GET_RESPOSTAOrdenado = " SELECT ID_ALUNO, ID_PERGUNTA, ID_OPCAO, VALOR, ID_OPCAO_PESSOA  FROM RESPOSTA ";
	
	
	public static String GET_CONFIGURACAO = " SELECT ID_CLIENTE, ID_PESQUISA, DSC_PESQUISA, AUTOMATICO, PREVISAO FROM CONFIGURACAO ";

	public static String GET_PERGUNTA_DESCRICAO =
			" SELECT ID_PERGUNTA, DESCRICAO, ID_BLOCO " +
					" FROM PERGUNTAS  " +
					" WHERE ID_PERGUNTA = ? ";

	public static String GET_RESPOSTA_SUBFORMULARIO = " SELECT DISTINCT R.ID_OPCAO_PESSOA FROM RESPOSTA R, PERGUNTAS P WHERE P.ID_PERGUNTA = R.ID_PERGUNTA AND R.ID_ALUNO = ? AND P.NUM_SUBFORMULARIO = ? AND R.ID_OPCAO_PESSOA > 0 order by R.ID_OPCAO_PESSOA ";

	public static String GET_RESPOSTA_SUBFORMULARIO_preenchido = " SELECT ID_OPCAO_PESSOA FROM RESPOSTA WHERE ID_ALUNO = ? AND ID_PERGUNTA = ? order by ID_OPCAO_PESSOA ";


	public static String GET_PERGUNTA_CHECK01 = "  SELECT ID_PERGUNTA FROM RESPOSTA WHERE ID_ALUNO =  ?  ";

	/////////
	//QUANDO TIVER MAIS DE UM BOTÃO
	///////
	//public static String GET_PERGUNTA_CHECK03 = "  SELECT ID_PERGUNTA FROM RESPOSTA WHERE ID_ALUNO =  ? AND (ID_PERGUNTA >=  10 AND ID_PERGUNTA <= 125) ";



	public static String GET_RESPOSTA_personalizado = " SELECT R.ID_ALUNO, R.ID_PERGUNTA, R.ID_OPCAO, O.VALOR AS VALOROPCAO, R.VALOR AS VALORRESPOSTA   FROM RESPOSTA R, OPCAO O "+
			" WHERE R.ID_OPCAO = O.ID_OPCAO AND R.ID_ALUNO = ? AND (R.ID_PERGUNTA >=   ? AND R.ID_PERGUNTA <= ?) and (R.ID_OPCAO_PESSOA IS NULL OR R.ID_OPCAO_PESSOA = 0) ORDER BY R.ID_PERGUNTA, R.ID_OPCAO  ";


}
